### ISSUE TITLE
"affinity is required for this operation" when trying to create new VM using XenServer provider

### ISSUE THREAD

**Issue by gdud** [chef/chef-provisioning-fog#123]
When I'm trying to create new virtual miachine using XenServer provider, I'm getting an error on the very beggining of the chef run:

```
- creating machine grzechu_fog_linux on fog:XenServer:xen-dc4-dev
    -   image_id: "c5952eb0-bd56-2a80-bcef-9415e52f3e40"
    -   affinity: "xen-dc4-dev"
    -   tags: {"Name"=>"grzechu_fog_linux", "BootstrapId"=>"https://.../organizations/.../nodes/grzechu_fog_linux", "BootstrapHost"=>"c52951", "BootstrapUser"=>"..."}
    -   name: "grzechu_fog_linux"[fog][WARNING] Unrecognized arguments: xenserver_redirect_to_master, affinity

    ================================================================================
    Error executing action `converge` on resource 'machine[grzechu_fog_linux]'
    ================================================================================
    
    ArgumentError
    -------------
    affinity is required for this operation
    
    Resource Declaration:
    ---------------------
    # In /Users/.../.chef/local-mode-cache/cache/cookbooks/cse_cluster/recipes/testenv_fog.rb
    
     44: machine "#{env_name}_linux" do
     45:   machine_options machine_options
     46:   role 'linux_dev_server'
     47: end
     48:

(..)
    
[2015-09-13T06:54:31+02:00] INFO: Running queued delayed notifications before re-raising exception
[2015-09-13T06:54:31+02:00] DEBUG: Re-raising exception: ArgumentError - machine[grzechu_fog_linux] (cse_cluster::testenv_fog line 44) had an error: ArgumentError: affinity is required for this operation
/Users/.../git/fog-core/lib/fog/core/attributes.rb:155:in `requires'
  /Users/.../git/fog-xenserver/lib/fog/compute/xen_server/models/instance_methods.rb:15:in `require_creation_attributes'
  /Users/.../git/fog-xenserver/lib/fog/compute/xen_server/models/instance_methods.rb:23:in `save' 
```

Looks like the affinity argument is not passing to the Fox XenServer module, but it is required.

fog/compute/xen_server/requests/set_affinity_server.rb:
```
(..)
require_before_save :name, :affinity
(..)
```

**Comment by diegobill** [comment]
:+1:

**Comment by jjasghar** [comment]
I guess this is still an issue. I'll attempt to build a xen server today to try to repo this.

**Comment by jjasghar** [comment]
Looking at the code, [this](https://github.com/chef/chef-provisioning-fog/blob/master/lib/chef/provisioning/fog_driver/providers/xenserver.rb#L66-L72) is the only reference to `:affinity`. 

My guess is that [this save](https://github.com/chef/chef-provisioning-fog/blob/master/lib/chef/provisioning/fog_driver/providers/xenserver.rb#L64) is out of order? I'm looking for a Xen instance to test against but I'm not having much luck. @diegobill or @gdud can you test/verify that it's just an ordering problem?

**Comment by diegobill** [comment]
@jjasghar, how can i test? What command to execute?

**Comment by jjasghar** [comment]
@diegobill that's a great question. I guess because you :+1:'d the issue you saw it. I created https://github.com/jjasghar/chef-provisioning-fog-example which covers digitalocean and openstack, maybe you can change the recipes for xen? If you do, I'd love to see xen support, and more then willing to accept a PR, in that repo too.

You'll have to probably check out the this repo, run `bundle install` and `bundle exec` and attempt to move the code around.

**Comment by jjasghar** [comment]
@kongslund do you have any thoughts on this?

**Comment by kongslund** [comment]
Seems like the Fog XenServer API has changed?

I am not actively working with XenServer at the moment and do not have the opportunity to investigate further. Chef DK 0.9 may do the trick for now.

**Comment by eclansky** [comment]
I'm getting the dreaded 'ERROR: ArgumentError: affinity is required for this operation'
when trying to create a vm with 'knife xenserver vm create' also...no luck, anybody have a solution or ideas?

**Comment by jjasghar** [comment]
@eclansky lovely. Can you debug any farther on this? I don't have access to xen server.

Not to mention we need to document the way to use xen server with c-p-fog.

**Comment by pealthoff** [comment]
I changed my fog version (1.35.0 -> 1.34.0) and fog-core (1.35.0 -> 1.32.1), then the error stoped.

**Comment by jjasghar** [comment]
Ah so this is something on the fog side? Any chance you've looked at the diffs to see what changed? 

We split out the openstack portion of to fog-openstack now, so we could probably do an upstream patch to fix this.

I'll take note of the differences here too.

**Comment by jjasghar** [comment]
Oh woah!

This was Xen not OpenStack, sorry about that.

**Comment by jjasghar** [comment]
We may have to wait for upstream to fix this if @pealthoff is correct on this. Lets see if we get more reports.

**Comment by jjasghar** [comment]
Confirmed from upstream.

**Comment by plribeiro3000** [comment]
What is need to do here to close this issue? cc/ @jjasghar

**Comment by jjasghar** [comment]
Stale issue, please reopen if this discussion needs to continue.

**Comment by plribeiro3000** [comment]
@jjasghar Sure. Was going over an old issue on `fog-xenserver` and realized this one was still open.
