### ISSUE TITLE
Using bootstrap_options for DigitalOcean breaks on versions > 0.16.0

### ISSUE THREAD

**Issue by razor-x** [chef/chef-provisioning-fog#182]
The below will work on chef-provisioning-fog v0.16.0, but fails on v0.17.0 and v0.18.0 with

```
ArgumentError
-------------
wrong number of arguments (given 1, expected 0)

Resource Declaration:
---------------------
# In test.rb

 27: machine 'test-node.otrcld.com' do
 28:   action :converge
 29: end
```

```ruby
require 'chef/provisioning'
require "chef/provisioning/fog_driver/recipe_dsl"

with_chef_server Chef::Config.chef_server_api,
  client_name: Chef::Config.node_name,
  signing_key_filename: Chef::Config.client_key

with_driver 'fog:DigitalOcean'
fog_key_pair Chef::Config.chef_organization

with_machine_options(
  convergence_options: {
    chef_version: "12.9.41"
  },
  bootstrap_options: {
    image: 'centos-7-0-x64',
    flavor_name: '2GB',
    region_name: 'San Francisco 1'
  }
)

machine 'test-node.otrcld.com' do
  action :converge
end
```

Looks like chef-provisioning-fog v0.17.0 uses fog v1.38.0 which I believe made a breaking change that is causing this error.

Seems like [line 75 in lib/chef/provisioning/fog_driver/providers/digitalocean.rb](https://github.com/chef/chef-provisioning-fog/blob/v0.18.0/lib/chef/provisioning/fog_driver/providers/digitalocean.rb#L75)

```ruby
keys = compute.ssh_keys.select { |k| k.name == bootstrap_options[:key_name] }
```

is calling `ssh_keys` in a way that doesn't work with 1.38.0. It only gets called when I customize the `bootstrap_options`. If I leave them empty, then it fails before it ever gets to line 75 because of an outdated default with

```
No images on DigitalOcean with distribution "CentOS" and name "6.5 x64"
```

Here is the relevant part of the stack trace:

```
ArgumentError: machine[test-node.otrcld.com] (@recipe_files::test.rb line 27) had an error: ArgumentError: wrong number of arguments (given 1, expected 0)
/home/razorx/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fog-1.38.0/lib/fog/digitalocean/requests/compute_v2/list_ssh_keys.rb:5:in `list_ssh_keys'
/home/razorx/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fog-1.38.0/lib/fog/digitalocean/models/compute_v2/ssh_keys.rb:17:in `all'
/home/razorx/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fog-core-1.38.0/lib/fog/core/collection.rb:113:in `lazy_load'
/home/razorx/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fog-core-1.38.0/lib/fog/core/collection.rb:28:in `select'
/home/razorx/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/chef-provisioning-fog-0.18.0/lib/chef/provisioning/fog_driver/providers/digitalocean.rb:75:in `bootstrap_options_for'
/home/razorx/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/chef-provisioning-fog-0.18.0/lib/chef/provisioning/fog_driver/driver.rb:319:in `block in create_servers'
/home/razorx/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/chef-provisioning-fog-0.18.0/lib/chef/provisioning/fog_driver/driver.rb:297:in `each'
/home/razorx/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/chef-provisioning-fog-0.18.0/lib/chef/provisioning/fog_driver/driver.rb:297:in `create_servers'
/home/razorx/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/chef-provisioning-fog-0.18.0/lib/chef/provisioning/fog_driver/driver.rb:191:in `allocate_machine'
/home/razorx/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/chef-provisioning-1.7.0/lib/chef/provider/machine.rb:31:in `block in <class:Machine>'
(eval):2:in `block in action_allocate'
/home/razorx/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/chef-12.9.41/lib/chef/provider.rb:360:in `instance_eval'
/home/razorx/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/chef-12.9.41/lib/chef/provider.rb:360:in `compile_and_converge_action'
```

**Comment by jjasghar** [comment]
Lovely. If you have a PR/fix i'm all ears. Otherwise I'll have to circle back here at some point.

**Comment by razor-x** [comment]
@jjasghar Right. Ran out of time to dig though it any more today, and figured I'd writeup what I had so far. Just looking at [the diff](https://github.com/fog/fog/compare/v1.37.0...v1.38.0), 1.38.0 touched a lot of the DO stuff, including the ssh_key parts. Maybe someone more familiar with the Compute libs can spot what happened.

**Comment by jjasghar** [comment]
Hmmm, ok, so are you suggestion to revert https://github.com/fog/fog/commit/a2c94a8c3f63c66f41ebf16417a4cf7e47065d70 @IvanChepurnyi ? 

I'm not 100% sure what to do here.

**Comment by IvanChepurnyi** [comment]
You need to exclude  v1.38.0 of fog from dependencies. As  v1.37.0 does not have this bug. Also  v1.39.0 will have the problem fixed, according to the commits history, but it is not released yet.

**Comment by jjasghar** [comment]
You should be able to work with what I said in https://github.com/chef/chef-provisioning-fog/issues/191.

Please reopen if it still continues.
