### ISSUE TITLE
vCair driver incompatible with Cheffish 5.0

### ISSUE THREAD

**Issue by monkey1016** [chef/chef-provisioning-fog#209]
The change in #208 makes it incompatible with the vCloud Air driver:

```
[2017-03-20T14:40:27-04:00] DEBUG: Re-raising exception: ArgumentError - vcair_app[order] (order::provision line 3) had an error: ArgumentError: machine_batch[order cluster start] (/Users/kj/.chef/local-mode-cache/cache/cookbooks/vcair_provisioning/resources/vcair_app.rb line 51) had an error: ArgumentError: wrong number of arguments (given 0, expected 1..2)
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/mixlib-config-2.2.4/lib/mixlib/config.rb:255:in `default'
  /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/ohai-8.22.1/lib/ohai/mash.rb:179:in `from_hash'
  /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/cheffish-5.0.1/lib/cheffish/merged_config.rb:6:in `block in initialize'
  /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/cheffish-5.0.1/lib/cheffish/merged_config.rb:6:in `map'
  /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/cheffish-5.0.1/lib/cheffish/merged_config.rb:6:in `initialize'
  /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-fog-0.24.0/lib/chef/provisioning/fog_driver/providers/vcair.rb:446:in `new'
  /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-fog-0.24.0/lib/chef/provisioning/fog_driver/providers/vcair.rb:446:in `compute_options_for'
```

What's the proper way to use `Cheffish::MergedConfig.new`?  @lamont-granquist Something in the changes to Cheffish don't mesh well with how it's being used in the vCair Driver [vcair.rb#L446](https://github.com/chef/chef-provisioning-fog/blob/master/lib/chef/provisioning/fog_driver/providers/vcair.rb#L446). I can submit a pull request to get it working if someone can point me in the right direction.

**Comment by lamont-granquist** [comment]
MergedConfig is a Mash now instead of a Hash so that symbol keys are all converted to strings, and you can write either one.

**Comment by nandanhegde73** [comment]
This issue or pull request is being automatically closed because the repository is being archived as part of the [Repository Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025).
