### ISSUE TITLE
Documentation says to require 'chef/provisioning/fog_driver' but you actually must load 'chef/provisioning/fog_driver/driver'

### ISSUE THREAD

**Issue by irvingpop** [chef/chef-provisioning-fog#92]
This seems weird and out of sync with the other chef-provisioning drivers (or maybe I haven't looked at them all yet).

```
LoadError
---------
cannot load such file -- chef/provisioning/fog_driver
```

**Comment by bplunkert** [comment]
I think the usage around this may have changed recently. Instead of the above I use this slightly simpler method:
```require 'chef/provisioning'```

Then before running ```chef-client -z``` I do: ```export CHEF_DRIVER=fog:DigitalOcean```.

My Gemfile:
```
gem 'chef-provisioning'
gem 'chef-provisioning-fog'
gem 'chef-provisioning-vagrant'
```

**Comment by irvingpop** [comment]
so, FWIW, this project's own spec tests fail with the same error (facepalm)

```
$ rspec
/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- chef/provisioning/fog_driver (LoadError)
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /oc/src/chef-provisioning-fog/spec/spec_helper.rb:5:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /oc/src/chef-provisioning-fog/spec/unit/fog_driver_spec.rb:1:in `<top (required)>'
       ....
```

**Comment by jjasghar** [comment]
I havent been able to repo this, and it's probably been taken care of upstream. If not please reopen it :)
